import { AsyncPushStream } from "./type";
import { Action, AsyncAction, Selector, AsyncSelector, Predicate, AsyncPredicate, Aggregate, AsyncAggregate } from "../type";
import { Executor } from "./push/async/type";
export declare const create: <T, Te = never>(executor: Executor<T, Te>) => AsyncPushStream<T, Te>;
export declare const createFrom: <T>(i: Iterable<T>) => AsyncPushStream<T, any>;
export declare function forEach<T>(s: AsyncPushStream<T, any>, f: Action<T> | AsyncAction<T>): void;
export declare function map<T, Te, K>(f: Selector<T, K> | AsyncSelector<T, K>): (s: AsyncPushStream<T, Te>) => AsyncPushStream<K, Te>;
export declare function filter<T, Te>(f: Predicate<T> | AsyncPredicate<T>): (s: AsyncPushStream<T, Te>) => AsyncPushStream<T, Te>;
export declare function remove<T, Te>(f: Predicate<T> | AsyncPredicate<T>): (s: AsyncPushStream<T, Te>) => AsyncPushStream<T, Te>;
export declare function take<T, Te>(n: number): (s: AsyncPushStream<T, Te>) => AsyncPushStream<T, Te>;
export declare function takeWhile<T, Te>(f: Predicate<T> | AsyncPredicate<T>): (s: AsyncPushStream<T, Te>) => AsyncPushStream<T, Te>;
export declare function skip<T, Te>(n: number): (s: AsyncPushStream<T, Te>) => AsyncPushStream<T, Te>;
export declare function skipWhile<T, Te>(f: Predicate<T> | AsyncPredicate<T>): (s: AsyncPushStream<T, Te>) => AsyncPushStream<T, Te>;
export declare function partition<T, Te>(n: number): (s: AsyncPushStream<T, Te>) => AsyncPushStream<T[], Te>;
export declare function partitionBy<T, Te>(f: Selector<T, any>): (s: AsyncPushStream<T, Te>) => AsyncPushStream<T[], Te>;
export declare const flatten: <T, Te>(s: AsyncPushStream<T[], Te>) => AsyncPushStream<T, Te>;
export declare function incubate<T, Te>(s: AsyncPushStream<Promise<T>, Te>): AsyncPushStream<T, Te>;
export declare function concat<T, Te>(s1: AsyncPushStream<T, Te>, s2: AsyncPushStream<T, Te>): AsyncPushStream<T, Te>;
export declare function concatAll<T, Te>([s, ...ss]: AsyncPushStream<T, Te>[]): AsyncPushStream<T, Te>;
export declare function zip<T, Te>(ss: AsyncPushStream<T, Te>[]): AsyncPushStream<T[], Te>;
export declare function race<T, Te>(ss: AsyncPushStream<T, Te>[]): AsyncPushStream<T, Te>;
export declare function reduce<T, K>(s: AsyncPushStream<T>, f: Aggregate<T, K> | AsyncAggregate<T, K>, v: K): Promise<K>;
export declare function count(s: AsyncPushStream<any>): Promise<number>;
export declare function include<T>(s: AsyncPushStream<T>, v: T): Promise<boolean>;
export declare function every<T>(s: AsyncPushStream<T>, f: Predicate<T> | AsyncPredicate<T>): Promise<boolean>;
export declare function some<T>(s: AsyncPushStream<T>, f: Predicate<T> | AsyncPredicate<T>): Promise<boolean>;
export declare function first<T>(s: AsyncPushStream<T>): Promise<void | T>;
export declare function last<T>(s: AsyncPushStream<T>): Promise<void | T>;
