import { AsyncPushStream } from "./type";
import { Action, AsyncAction, Selector, AsyncSelector, Predicate, AsyncPredicate, Aggregate, AsyncAggregate } from "../type";
import { Executor } from "./push/async/type";
export declare const create: <T = never>(executor: Executor<T>) => AsyncPushStream<T>;
export declare const createFrom: <T>(i: Iterable<T>) => AsyncPushStream<T>;
export declare function forEach<T>(s: AsyncPushStream<T>, f: Action<T> | AsyncAction<T>): void;
export declare function map<T, K>(f: Selector<T, K> | AsyncSelector<T, K>): (s: AsyncPushStream<T>) => AsyncPushStream<K>;
export declare function filter<T>(f: Predicate<T> | AsyncPredicate<T>): (s: AsyncPushStream<T>) => AsyncPushStream<T>;
export declare function remove<T>(f: Predicate<T> | AsyncPredicate<T>): (s: AsyncPushStream<T>) => AsyncPushStream<T>;
export declare function take<T>(n: number): (s: AsyncPushStream<T>) => AsyncPushStream<T>;
export declare function takeWhile<T>(f: Predicate<T> | AsyncPredicate<T>): (s: AsyncPushStream<T>) => AsyncPushStream<T>;
export declare function skip<T>(n: number): (s: AsyncPushStream<T>) => AsyncPushStream<T>;
export declare function skipWhile<T>(f: Predicate<T> | AsyncPredicate<T>): (s: AsyncPushStream<T>) => AsyncPushStream<T>;
export declare function partition<T>(n: number): (s: AsyncPushStream<T>) => AsyncPushStream<T[]>;
export declare function partitionBy<T>(f: Selector<T, any>): (s: AsyncPushStream<T>) => AsyncPushStream<T[]>;
export declare const flatten: <T>(s: AsyncPushStream<T[]>) => AsyncPushStream<T>;
export declare function _flatten<T>(): (s: AsyncPushStream<T[]>) => AsyncPushStream<T>;
export declare function incubate<T>(s: AsyncPushStream<Promise<T>>): AsyncPushStream<T>;
export declare function _incubate<T>(): (s: AsyncPushStream<Promise<T>>) => AsyncPushStream<T>;
export declare function concat<T>(s1: AsyncPushStream<T>, s2: AsyncPushStream<T>): AsyncPushStream<T>;
export declare function concatAll<T>([s, ...ss]: AsyncPushStream<T>[]): AsyncPushStream<T>;
export declare function zip<T>(ss: AsyncPushStream<T>[]): AsyncPushStream<T[]>;
export declare function race<T>(ss: AsyncPushStream<T>[]): AsyncPushStream<T>;
export declare function reduce<T, K>(s: AsyncPushStream<T>, f: Aggregate<T, K> | AsyncAggregate<T, K>, v: K): Promise<K>;
export declare function count(s: AsyncPushStream<any>): Promise<number>;
export declare function include<T>(s: AsyncPushStream<T>, v: T): Promise<boolean>;
export declare function every<T>(s: AsyncPushStream<T>, f: Predicate<T> | AsyncPredicate<T>): Promise<boolean>;
export declare function some<T>(s: AsyncPushStream<T>, f: Predicate<T> | AsyncPredicate<T>): Promise<boolean>;
export declare function first<T>(s: AsyncPushStream<T>): Promise<void | T>;
export declare function last<T>(s: AsyncPushStream<T>): Promise<void | T>;
